###
POST http://localhost:9000/api/nominas HTTP/1.1
Content-Type: application/json

{
  "nombre": "Angela",
  "apellido": "Suarez",
  "foto": "ruta/a/la/foto.jpg",
  "correo": "Angela.Suarez@example.com",
  "direccion": "Calle 199a, Cali",
  "cargo": "Proyect",
  "salario": 75000
}
###
GET  http://localhost:9000/api/nominas HTTP/1.1

###
GET  http://localhost:9000/api/nominas/6563e1ca6e7a44df4bac819f HTTP/1.1

###
PUT http://localhost:9000/api/nominas/6563e1ca6e7a44df4bac819f HTTP/1.1
Content-Type: application/json

{
  "nombre": "Angela",
  "apellido": "Suarez",
  "foto": "ruta/a/la/foto.jpg",
  "correo": "Angla.Suarez@example.com",
  "direccion": "Calle 200, Cali",
  "cargo": "Proyect",
  "salario": 55000
}
###
DELETE http://localhost:9000/api/nominas/6563e1ca6e7a44df4bac819f HTTP/1.1